version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: tutorial
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - /Users/enniobastos/Documents/projects/tutorial-thiago/data:/var/lib/postgresql/data
    ports:
      - "5432:5432" #forwarding the port to the host machine

volumes:
  postgres_data:
